# GitHub Sponsors - Primary sponsorship platform
# To enable: Sign up at https://github.com/sponsors
github: exabird

# Uncomment and add your usernames once accounts are created:
# ko_fi: exabird
# buy_me_a_coffee: exabird
# custom: ["https://paypal.me/exabird"]
